### ISSUE TITLE
Compose should provide a platform independent way to create an ImageBitmap from an encoded byte array

### ISSUE THREAD

**Issue by mipastgt** [JetBrains/compose-multiplatform#1113]
Compose should provide a platform independent way to create an ImageBitmap from an encoded byte array. Currently the programmer has to manage that himself on a per-platform basis.

On Android I use
```
override fun imageBitmapFromBytes(encodedImageData: ByteArray): ImageBitmap {
    val bitmap = BitmapFactory.decodeByteArray(encodedImageData, 0, encodedImageData.size)
    return bitmap.asImageBitmap()
}
```
and on Desktop I use
```
override fun imageBitmapFromBytes(encodedImageData: ByteArray): ImageBitmap {
    return Image.makeFromEncoded(encodedImageData).asImageBitmap()
}
```
but I think something like this actually belongs into Compose itself.

See discussion on Slack: https://kotlinlang.slack.com/archives/C01D6HTPATV/p1629903092435000

**Comment by abueide** [comment]
i banged my head against my gradle files trying everything for 3 hours till I found this ticket (i'm not very smart) and realized that  makeFromEncoded and toComposeBitmapImage are not available on android, yet I can still call them from my commonMain sourceset for some reason.

really would like this feature since I am using images in my resources folder (mapped to the assets folder on android) and I need some way to display them on android.

thanks <3

**Comment by chrisjenx** [comment]
I agree, util method to go from ByteArray or Channel to ImageBitmap would be really helpful.
