### ISSUE TITLE
Apps always only start on the primary display

### ISSUE THREAD

**Issue by rock3r** [JetBrains/compose-multiplatform#1224]
When you start an app from the IDE, it always shows on the primary display on Windows 10. There's no way that I can see to make it start on the same display as the IDE is on (I usually keep the IDE on the secondary display)

**Comment by rock3r** [comment]
Would add to this, there seems to be no way to choose which display a window or dialog is shown on. If you open a dialog or window, it always opens on the main display, even if the app is on another display (and the user focus also is), which is not great UX.

**Comment by rock3r** [comment]
Thanks for looking into it @igordmn 🙌

**Comment by igordmn** [comment]
In https://github.com/JetBrains/compose-jb/issues/1845 we show the new window on the same display, where the previous window was. But we still show the very first window on the default display, because we can't know the display of the previous process (IDEA in our case). At least I don't know how we can implement that.

I plan to extend API for manual display choosing (not in 1.2.0). Then you will be able to add something like `-Pdisplay=2` in your run configuration.

**Comment by rock3r** [comment]
That sounds like a perfectly valid solution for the problem 👍

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6103">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
