### ISSUE TITLE
Is there already a map control?

### ISSUE THREAD

**Issue by D10NGYANG** [JetBrains/compose-multiplatform#1341]
I need to display a map, how should I do it, load the page? But I can't find the web control either

**Comment by yaroslavkulinich** [comment]
Try to use available Swing components for maps

**Comment by Lewik** [comment]
@yaroslavkulinich do you have any code for map?

**Comment by yaroslavkulinich** [comment]
I use Swing-based WorldWindJava 3d gis library.
But it's not the best way if you need just to show something on a map. It's for more complex 3d map apps and requires deep reconfigurations, because written pretty old style, for old use cases and techniques. 
To use map with compose - wrap some Swing map panel into SwingPanel composable.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5204">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
