### ISSUE TITLE
AlertDialog: title+text layout error when focus changes

### ISSUE THREAD

**Issue by sergeych** [JetBrains/compose-multiplatform#1583]
When the alert dialog text contains several TextFields in a column, when topmost received and looses focus layout changes making title part to stretch to text part even ignoring title's padding settings, unless the topmost TextEdit have some text in it. See attached video: 

https://user-images.githubusercontent.com/300065/145812239-0778a2b4-4280-4243-bdda-2f53760c945a.mov

Code fragment:
~~~kotlin
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.paddingFromBaseline
import androidx.compose.material.AlertDialog
import androidx.compose.material.ExperimentalMaterialApi
import androidx.compose.material.OutlinedTextField
import androidx.compose.material.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.em

@OptIn(ExperimentalMaterialApi::class)
@Composable
fun LayoutDialogErrorDemo() {
    var t1: String by remember { mutableStateOf("") }
    var t2: String by remember { mutableStateOf("") }
    AlertDialog(
        {},
        title = { Text("The Heading",fontSize = 1.4.em, modifier = Modifier.paddingFromBaseline(6.dp,4.dp)) },
        buttons = { Text("No buttons") },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                OutlinedTextField(t1, { t1 = it }, label = { Text("Field1") })
                OutlinedTextField(t2, { t2 = it }, label = { Text("Field2") })
            }
        }
    )
}
~~~

**Comment by jakobkmar** [comment]
It seems like just in general any top padding is ignored.

**Comment by m-sasha** [comment]
> It seems like just in general any top padding is ignored.

Yes, unfortunately this is how an `AlertDialog` works, by design. It uses the baselines of the `title` and `text` to position them, which has the effect of ignoring their vertical padding.

Alert dialogs are only meant to be used with `Text` content: https://partnerissuetracker.corp.google.com/issues/217151230#comment7

We are working on a more general "Dialog" implementation. In the meanwhile, you can use the `PopupDialog` I posted [here](https://github.com/JetBrains/compose-multiplatform/issues/2531#issuecomment-1456807469).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5132">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
