### ISSUE TITLE
How to get current working dir on MacOs in compose desktop?

### ISSUE THREAD

**Issue by thelou1s** [JetBrains/compose-multiplatform#1960]
I wanna get current working dir, in order to call some commands. I copied code from jetpack compose desktop lib's demo, but got wrong dir("/"). Could any one tell me what's the problem? thank you.

(jetpack compose desktop lib: https://github.com/JetBrains/compose-jb/blob/master/tutorials/Native_distributions_and_local_execution/README.md)

```
                        val userDirStr = File(System.getProperty("user.dir"))
                        if (userDirStr != null) {
                            println("Row, onGloballyPositioned, userDirStr = " + userDirStr)
                            outputText = "directory = " + userDirStr
                        }
```

**Comment by AlexeyTsvetkov** [comment]
@thelou1s 
The code seems to be correct (you can also simply use `File("").absoluteFile` since JVM resolves relative paths relative to a working directory). However, I'm not sure, what do you expect a working directory of a graphical application to be?
A working directory "is typically the directory in which the Java virtual machine was invoked." When launched from a console, it will be a normal terminal emulator's working directory.
However, usually graphical applications are launched via some other application (e.g. Finder on macOS, explorer on Windows). In that case, a working directory may be a working directory of a "parent" application (but generally it seems to be platform specific).
Could you provide more details about your use case?

**Comment by thelou1s** [comment]
I build a new Compose Crossplatform project, and copy old code into it. Then "File(System.getProperty("compose.application.resources.dir"))" just got the right path.

https://stackoverflow.com/questions/71316296/how-to-get-current-working-dir-on-macos-in-compose-desktop

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1960">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
