### ISSUE TITLE
Textfield text not centered vertically

### ISSUE THREAD

**Issue by CarsonRedeye** [JetBrains/compose-multiplatform#202]
Build-135. MacOS 11.0.1

```
fun main() = Window {
    var textFieldValue by remember { mutableStateOf("Hi") }
    OutlinedTextField(
        textFieldValue,
        { textFieldValue = it }
    )
}
```
 
<img width="288" alt="Screen Shot 2020-12-19 at 5 41 13 pm" src="https://user-images.githubusercontent.com/44560503/102684191-80afda00-422a-11eb-8c8a-560bd82e5550.png">

**Comment by Metric-Void** [comment]
There's an argument called ```singleLine``` which defaults to ```false```. Changing that may help

**Comment by Chozzle** [comment]
My mac died so I can't test it. Regardless it's a bug, because the same behaviour doesn't appear when running on MS Windows

**Comment by remcomokveld** [comment]
Although it isn't exactly the same issue since the OP does not specify the `label` parameter, I'm running into this issue as well when setting a label. It seems to be because the padding will in that case be set to `top = 8.dp, bottom = 0.dp` which means that effectively the text is centered, but due to the top of the outline being pushed down by 8 dp it looks to be visually off.

**Comment by hamthelegend** [comment]
I had the same problem but turning on singleline helped. Thank you

**Comment by adurandet** [comment]
I still have this issue for multiline textfield. :/

**Comment by natansalda** [comment]
Same issue here in new year too :)

**Comment by m-sasha** [comment]
Ok, so the problem here is a combination of several things:
1. On Android, the height of a line of text at the default font size is larger than on the desktop.
2. The `TextFieldDefaults.MinHeight`, however, is set on both Android and desktop to `56.dp`
3. When `singleLine=false`, the text is top-aligned. When `singleLine=true`, it's center-aligned.

So on Android, a top-aligned larger text seems centered vertically, completely by accident. You can see this by setting the fontSize to be smaller:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/5230206/217671207-09e68325-1c81-4c3e-9819-155f54f70ea7.png">


On the desktop, it doesn't look centered vertically because of the smaller text height.

@igordmn Maybe we should adjust `TextFieldDefaults.MinHeight` to a smaller value. The height of text fields does seem too big relative to the text, and even in absolute terms. Text fields on the desktop are typically much smaller, and I'm not even sure what the point is to give a minimum height to a text field as it's not going to be pressed with a finger.

<img width="416" alt="SCR-20230209-1dp" src="https://user-images.githubusercontent.com/5230206/217670868-51acba37-c483-4557-9bac-c180b8641d4c.png">

<img width="288" alt="SCR-20230209-1dg" src="https://user-images.githubusercontent.com/5230206/217670891-8498d9b6-a9de-452c-b1c4-b78ef4e67e0d.png">


By the way, if you use `MaterialTheme`, the text gets larger and the problem goes away:

<img width="287" alt="SCR-20230209-1d2" src="https://user-images.githubusercontent.com/5230206/217670921-372e13d9-e27b-427f-9dba-022910a0105e.png">

**Comment by m-sasha** [comment]
By the way, you can easily work around this issue by setting `Modifief.heightIn(1.dp)` (but not `0.dp`) on the text field. This will override the `TextFieldDefaults.MinHeight` and the textfield will always be sized to wrap the text inside (including the `PaddingValues`, of course).

**Comment by m-sasha** [comment]
So, after consulting with Google, the thing is that `OutlinedTextField` is a Material widget, and so it's optimized for mobile. When compose for desktop will have a proper desktop theme, it will have the appropriate min-height value.

For now, if you're going to use Material widgets on the desktop, you will need to sometimes deal with inconsistencies like that, unfortunately. Luckily, this particular issue has a simple workaround.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6056">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
