### ISSUE TITLE
Unresolved reference: OutlinedTextField (material3)

### ISSUE THREAD

**Issue by lucasmeneghin** [JetBrains/compose-multiplatform#2176]
Looks like OutlinedTextField (and maybe more) is missing from material3 for android.

Project builds and run fine for desktop and web, fails for android.

Compose version: 1.2.0-alpha01-dev741
![image](https://user-images.githubusercontent.com/17552595/177877587-c217fbc5-9c0b-4ba5-ab48-762d8ea85340.png)

**Comment by lucasmeneghin** [comment]
Current workaround is to add 
api("androidx.compose.material3:material3:1.0.0-alpha14")
to android source set
Not sure if this could lead to problems with a release build, but should also be solvable

**Comment by alfianandinugraha** [comment]
I solve this by upgrade the material version to 
`implementation 'androidx.compose.material3:material3:1.0.0-beta03'`

**Comment by kavinchu** [comment]
I still get this issue with 
implementation 'androidx.compose.material3:material3:1.0.0' I tried changing it to alpha14 but still same error.
Where do I put the api(....)?

**Comment by kavinchu** [comment]
Figured it out need to add this annotation on the function
@OptIn(ExperimentalMaterial3Api::class)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2176">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by IjaasMohamed** [comment]
even with the gradle change - implementation("androidx.compose.material3:material3:1.0.0-alpha14")
its not working. is there a work around to solve this?

**Comment by MatkovIvan** [comment]
Multiplatform packages are `org.jetbrains.androidx.*` and usually available via plugin properties. Please refer to [documentation](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-multiplatform-create-first-app.html) instead of the outdated issue. 1.0.0-alpha is not the version you should use.

Since GitHub issues were closed with clear instructions to use YouTrack for follow-ups, so I'm going to lock this one
