### ISSUE TITLE
Weird Dialog/Window border behavior

### ISSUE THREAD

**Issue by lucasmeneghin** [JetBrains/compose-multiplatform#2187]
application {
        val windowState =
            rememberDialogState(height = 250.dp)
        Dialog(
            onCloseRequest = ::exitApplication,
            state = windowState,
            undecorated = true,
            transparent = true,
            resizable = false
        ) {
            Box(modifier = Modifier.fillMaxSize().border((1).dp, color = Color.Black)) {
            }
        }
    }

![image](https://user-images.githubusercontent.com/17552595/178804538-7b166601-087f-465d-80a4-23127c6c9024.png)

If transparent = false, the lower border is there, but it is thiner.

![image](https://user-images.githubusercontent.com/17552595/178804638-62e158fa-968d-4558-880f-63b39bd8be01.png)

transparent with height 251.dp

![image](https://user-images.githubusercontent.com/17552595/178804725-a38b2c3e-0dce-4475-8ebd-08ecf532f95d.png)

transparent  = false with 251.dp

![image](https://user-images.githubusercontent.com/17552595/178804835-511875b0-f6c5-4213-8f88-9e6cc9140442.png)

same with 252.dp

![image](https://user-images.githubusercontent.com/17552595/178804857-1dc728ab-e236-42d1-a16b-bfc3402d27bf.png)

Its not specific to those values, 450 dp transparent will also not produce a lower border and etc

**Comment by lizhongyue248** [comment]
Like same issue , I try to add shadow

```
application {
    val windowState =
        rememberDialogState(height = 250.dp)
    Dialog(
        onCloseRequest = ::exitApplication,
        state = windowState,
        undecorated = true,
        transparent = true,
        resizable = false
    ) {
        App(
            pageModifier = Modifier.fillMaxWidth()
                .shadow(20.dp, RoundedCornerShape(5.dp)),
            title = {
                WindowDraggableArea {
                    PageTitle()
                }
            }
        )
    }
}
```
I can get shadow, and must add padding to show shaodw.

Is there any follow-up on this issue?

**Comment by m-sasha** [comment]
The original issue is no longer reproducible 1.6.0-rc02

@lizhongyue248 Please file a new issue, and provide a complete, minimal reproducer (the code you posted is missing the definition of `App`).

**Comment by igordmn** [comment]
It is reproducible on non-integer system scale. On macOs it usually isn't possible to set, so it is needed to check on Windows/Linux.

Steps to reproduce:
1. set the system scale to 125% (on Windows it is in Display settings)
2. run the code:
```
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.singleWindowApplication

fun main() = singleWindowApplication(undecorated = true) {
    Box(modifier = Modifier.fillMaxSize().border((1).dp, color = Color.Red))
}
```
3. resize. some sizes results in a white line on the right/bottom
<img width="513" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/5963351/dbae5ed3-1ed2-4498-8055-7846996528fc">

(in `1.6.0-rc02` the hiding isn't reproducible, only the white line)

This happens, because the system resizes the window in pixels, but AWT reports the size in int points, and loses precision. The proper fix will be to read/subscribe to the size of the window via native code.

related issue: https://github.com/JetBrains/compose-multiplatform/issues/179 (slightly different because we had overlapping with system titlebar and window border)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2187">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
