### ISSUE TITLE
Theming @Preview Annotation

### ISSUE THREAD

**Issue by FrankDomburg** [JetBrains/compose-multiplatform#2222]
Wrapping my head around @Preview annotation in Android Studio (and hoisting state up)

What I don't like is that when I'd like to see previews in my app's theme, I need to wrap the preview in a theme and thus to have a separate @composable. Especially since I can do light/dark in the preview annotation's parameters.

In my view, the theme should be specifiable in the preview parameter (which is probably more generic as a solution), or default to using Material3. That way, the @Preview annotation and the actual definition of a @Composable can be combined in 99% of all cases.

**Comment by svenjacobs** [comment]
`MaterialTheme` or whatever theme you are using is a Composable because it provides a few crucial [CompositionLocals](https://developer.android.com/reference/kotlin/androidx/compose/runtime/CompositionLocal) that define colors, text styles, shapes etc. So I'm not sure if it's possible to pass this Composable just as an argument to the `@Preview` annotation and reduce boiler plate code. But hopefully you have created your own `AppTheme` Composable that wraps `MaterialTheme` and defines all your custom styles so that you don't have to repeat this for every preview.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2222">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
