### ISSUE TITLE
Use Flutter Engine (Impeller) as a Rending Backend

### ISSUE THREAD

**Issue by JsouLiang** [JetBrains/compose-multiplatform#2394]
Hello friends, do we have any planes to use the Flutter as a Rending Backend?
We can use Flutter's rendering pipeline, which is more efficient than calling the canvas interface directly

**Comment by igordmn** [comment]
If you talk about wrapping Flutter widgets to Composable functions in Kotlin, then we don't have such plans.

Maybe some third-party library will implement it. It will be an interested use of Compose Runtime :).

If you talk about using some part of Flutter inside Compose instead of some part of our rendering pipilene, then we don't have such plans too.

> which is more efficient than calling the canvas interface directly

Why do you think it will be more efficient? Flutter uses the same Skia Canvas underneath, so we will add just one more layer.

**Comment by kirill-grouchnikov** [comment]
Flutter is moving off of Skia - https://medium.com/flutter/announcing-flutter-3-3-at-flutter-vikings-6f213e068793

> Aside from the improvements in 3.3 itself, the team has been hard at work on [Impeller](https://github.com/flutter/engine/tree/main/impeller), our next-generation rendering layer.

> Impeller is a significant rewrite of a core part of the Flutter engine, replacing the previous Skia code with a custom runtime that takes full advantage of modern hardware-accelerated graphics APIs such as [Metal](https://developer.apple.com/metal/) on iOS and [Vulkan](https://developer.android.com/ndk/guides/graphics) on Android.

**Comment by JsouLiang** [comment]
> If you talk about wrapping Flutter widgets to Composable functions in Kotlin, then we don't have such plans.
NO, this not my mean.
My think is that if we can use the Flutter's C++ engine, we can use that C++ engine layer. A lot of rendering optimizations are done on a Layer basis, like partial repaint

**Comment by igordmn** [comment]
Thanks for the idea. Let's keep this issue open for now. It maybe not worth and feasible to completely replace Skia+Skiko by Flutter Engine because of the points above, but worth to investigate why Flutter did that, and can we use some techniques from Flutter Engine.

Partial repaint and layering itself isn't completely related to Skia, it usually implemented on top of it. Layering itself is already supported by Compose, we only need to support [partial repaint of the layers](https://github.com/JetBrains/skiko/issues/53)

**Comment by syy555** [comment]
Hi all，for this quesiton, I got another problem. As compose on iOS is in Alpha, we decide to write some demo page to share UI code on iOS and Android by using compose. However, the Skia size on iOS is huge, which increase the iOS App total size like 5~8MB. Is there any plan to solve this problem?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2394">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
