### ISSUE TITLE
Is there any way to shrink the compose 1.3 size

### ISSUE THREAD

**Issue by guoguo338** [JetBrains/compose-multiplatform#2599]
Even with minifyEnabled configured in Build.gradle file, a simple demo shows that 113k bytes package size is introduced after upgrading from compose 1.1 to 1.3. And in our product, 276k size improvement was seen. Is there any way to shrink the size? For example, is it possible to just disable some features?

**Comment by igordmn** [comment]
The only 2 things that come to my mind, and which are not available right now:
- get rid of Swing inside Compose, use native platform API
- split Skiko into separate libraries

Both require a lot of resources, so that won't be implemented in the near future.

Other than that, `minifyEnabled` is probably the only option right now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2599">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
