### ISSUE TITLE
ComposePanel visibility isn't taken into account

### ISSUE THREAD

**Issue by BoD** [JetBrains/compose-multiplatform#2656]
When hiding a `ComposePanel` or one of its parents, the last frame of the contained Compose UI remains visible.

Here's a simple reproducer showing the issue:

```kotlin
fun main() = SwingUtilities.invokeLater {
  val parentJPanel = JPanel(BorderLayout())
  parentJPanel.add(
    BorderLayout.CENTER,
    ComposePanel().apply {
      setContent {
        Button(
          onClick = {
            parentJPanel.isVisible = false // <- this hides this JPanel, but the button stays visible on screen
          }
        ) {
          Text("Hello World")
        }
      }
    }
  )

  JFrame().apply {
    setSize(800, 600)
    contentPane.add(parentJPanel)
    isVisible = true
  }
}
```

Here we have a JFrame containing a JPanel containing a ComposePanel containing a compose Button. Clicking the Button hides the JPanel - but the Button's UI remains visible.

**Comment by igordmn** [comment]
Compose 1.2.2

Reproducible on macOS, on Windows it behaves correctly

**Comment by LouisCAD** [comment]
Do you know what is the root cause?

**Comment by igordmn** [comment]
No, unfortunately. It need to be investigated. Under suspicion - we wrongly dispose graphic resources in Skiko for macOS, so we see a ghost of Compose application.

**Comment by robercoding** [comment]
Same issue, reproducible in 1.3.0 in macOS Monterrey 12.16.1 with M1 Pro.
Trying to follow Settings tutorial from Intellij plugin development documentation.
https://plugins.jetbrains.com/docs/intellij/settings-tutorial.html

In this specific case, using Compose to build the UI
![image](https://user-images.githubusercontent.com/66839423/221366362-a97c244f-cf5b-418e-a45b-8872631e537d.png)
![image](https://user-images.githubusercontent.com/66839423/221366366-388ccdca-aa74-42b9-ac89-04ed96f9cd7b.png)

Tried in my other PC using Windows and it's working as expected, the issue is only on mac OS

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2656">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
