### ISSUE TITLE
Pass certain library jars to proguard as -libraryjars instead of -injars

### ISSUE THREAD

**Issue by mcpiroman** [JetBrains/compose-multiplatform#2769]
Currently gradle plugin sends the whole application's classpath as `-injars` argument to proguard. 
But some, if not most dependencies are desirable to be put as `-libraryjars` instead, because of:
- licenses
- faster build
- avoiding processing problems such as lack of suitable rules for a given library

(In particular I cannot manage to process libraries such sa ojdbc11 library even with `-keep class`, `-dontwarn` and `-dontnote` rules.)

It could even be the default to pass all not-project and not-compose dependencies as -libraryjars with an option to specify which should actually be -injars.

**Comment by AlexeyTsvetkov** [comment]
> Currently gradle plugin sends the whole application's classpath as -injars argument to proguard.

@mcpiroman that's not entirely accurate. Currently the plugin sends the whole **runtime** classpath as `-injars`. These libraries are potentially needed at runtime, so basically you want us to exclude some libraries from the minification, and simply pack them in full?

> It could even be the default to pass all not-project and not-compose dependencies as -libraryjars with an option to specify which should actually be -injars.

I don't see a way to do this reliably in Compose Gradle Plugin. We get a reference to Kotlin runtime classpath as a `FileCollection`, which is just `Iterable<File>`. We could try to invent some heuristics, but, given Gradle's inherent customizability, all heuristics are going to fail.

I think adding a way to exclude some library from DSL is possible.  
But it should also be possible with wildcard keep rules like:
```
-keep class oracle.** { *; }
```

Also, since you have an issue with a jdbc library, have you trried including `java.sql` JDK module (in addition to the wildcard rules above)?

```

// build.gradle.kts
compose.desktop {
    application {
        nativeDistributions {
            // ...
            modules("java.sql")
        }
        buildTypes.release {
            proguard {
                configurationFiles.from("compose-desktop.pro")
            }
        }
    }
}
// compose-desktop.pro
-keep class oracle.** { *; }
```

**Comment by mcpiroman** [comment]
> you want us to exclude some libraries from the minification, and simply pack them in full?

Exactly

> I don't see a way to do this reliably in Compose Gradle Plugin

How about collecting output jars of all projects, something like `project.root.allProjects.flatMap { it.jar.outputFiles }` (syntax made up).


Now to my case with ojdbc:
Yes, I have tired all that you proposed. 
Currently I use my own gradle script run proguard and there I pass some libraries like ojdbc with -libraryjars and copy them as-is. So basically I would like to do the same but with the official proguard support.

**Comment by AlexeyTsvetkov** [comment]
> How about collecting output jars of all projects, something like `project.root.allProjects.flatMap { it.jar.outputFiles }` 

The proposed snippet won't work for all projects. It only looks at the `Jar` task, created by `java` plugin by default. Plugins or builds might define additional `Jar` tasks or produce jar files by other means.
  
Also `allProjects` most likely will be incompatible with Gradle's future project isolation.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2769">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
