### ISSUE TITLE
Desktop: `onKeyEvent` returns wrong key for `Key.Enter` (regression)

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#2861]
I discovered this issue trying to migrate a project from Compose Multiplatform `1.0.1-rc2` to `1.3.1` – the `Key.Enter` `keyCode` seems to be broken.

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 
- Compose Multiplatform version*: `1.3.1` (still worked fine in `1.0.1-rc2`)
- OS version(s)* (required for Desktop and iOS issues): macOS
- OS architecture (x86 or arm64): arm64
- JDK (for desktop issues): temurin 17

**To Reproduce**

```kotlin
import androidx.compose.desktop.ui.tooling.preview.Preview
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.ExperimentalComposeUiApi
import androidx.compose.ui.Modifier
import androidx.compose.ui.focus.FocusRequester
import androidx.compose.ui.focus.focusRequester
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.key.Key
import androidx.compose.ui.input.key.key
import androidx.compose.ui.input.key.onKeyEvent
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@OptIn(ExperimentalComposeUiApi::class)
@Composable
@Preview
fun App() {
    val requester = remember { FocusRequester() }
    Box(
        Modifier
            .fillMaxSize()
            .background(Color.Red)
            .onKeyEvent { keyEvent ->
                println("$keyEvent: ${keyEvent.key.keyCode} should be ${Key.Enter.keyCode}")
                false
            }
            .focusRequester(requester)
            .clickable { requester.requestFocus() }
    )
}

fun main() = application {
    Window(onCloseRequest = ::exitApplication) {
        App()
    }
}
```

Click the red square and press `return`.

```
KeyEvent(nativeKeyEvent=java.awt.event.KeyEvent[KEY_TYPED,keyCode=0,keyText=Unknown keyCode: 0x0,keyChar=⏎,keyLocation=KEY_LOCATION_UNKNOWN,rawCode=0,primaryLevelUnicode=0,scancode=0,extendedKeyCode=0xa] on canvas0): 536870912 should be 43486543872
```

The value returned by the `KEY_TYPED` event (`keyCode=536870912`) does not match the `Key.Enter` (`keyCode=43486543872`).

**Comment by m-sasha** [comment]
I'm not fully down to the root of the problem here, but here are a few things I know:
1. A `KEY_TYPED` event is supposed to have a 0 keyCode; that's normal. That type is only for events that generate a character.
2. You're only receiving `KEY_TYPED`, not `KEY_PRESSED` or `KEY_RELEASED` events for some reason, and the reason seems to be whatever `clickable` is doing. 
3. Since Compose 1.3, `Modifier.clickable` already makes the element focusable, and focuses it on click, so your requester, and the requesting of focus on click aren't needed.

If you don't use `clickable` but just `focusable(true)` and then request focus in a `LaunchedEffect`, it will work. You will receive KEY_PRESSED and KEY_RELEASED events.

If you use `Modifier.onKeyEvent{}.clickable{}`, it _won't_ work. You will only receive KEY_TYPED events.

If you use `Modifier.clickable{}.onKeyEvent{}`, it _will_ work. You will receive all types of events.

**Comment by m-sasha** [comment]
By the way, `536870912=0x20000000` and `43486543872=0xa20000000` and `Key.keyCode` is composed of the AWT key-code (1st 4 bytes) and AWT "key location" (last 4 bytes). So the mismatch is basically that you're getting a 0 native key code instead of `0xa` (which is the code for ENTER, or newline).

**Comment by m-sasha** [comment]
Ok, apparently this works "as intended".

`Modifier.clickable` does a bunch of somewhat unexpected things. One of those is it listens to a key-down ENTER event and consumes it. It does this because on the desktop ENTER is (logically) a "click", and it actually invokes the lambda you pass to `clickable` when you do that.

**Comment by SebastianAigner** [comment]
😱 So what's the `KeyEvent` that I am receiving, and why is it different from registering as an "Enter" key, even though the key event is represented as `⏎`? 🤔

**Comment by m-sasha** [comment]
You're receiving the KEY_TYPED event, and it's not supposed to have a keyCode. It's an AWT thing.

What you're expecting to receive is the KEY_PRESSED event, but it's consumed by clickable, so you're not receiving it.

You can use `onPreviewKeyEvent` instead, or one of the other ways to make it work.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2861">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
