### ISSUE TITLE
How to properly open a new window or switch between windows from code?

### ISSUE THREAD

**Issue by paulorb** [JetBrains/compose-multiplatform#2888]
I am creating a very simple (Desktop) application which consists in two Windows A and B.

A contains a button which when pressed should close the current window and open a new window B
B only has a Text (label)

How can I properly manage the window creation/termination directly from the Compose/Window code.  

What do you suggest? I saw some articles about Decompose, but I was looking for something more simple (since my application will have few windows)

**Comment by pablichjenkov** [comment]
I advice you to post this type of question in stackoverflow or in the kotlin slack channel. Here will create just noise, since this is not an issue but a question on how to use a specific feature of the framework.
Back to your question, you can have a list of WindowState in your Application and render the list all the time.

```kotlin
for (windowState in activeWindowsState) {
            key(windowState) {
                YourWindowCustomClass(windowState)
            }
        }
```
Then on the A button click you add WindowStateB to the list and remove WindowStateA from the windowstate list.

Check this [windowState](https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Window_API_new#open-and-close-multiple-windows)

Here is an example of similar functionality. Although it has some decoration on it: https://github.com/pablichjenkov/templato/blob/3ce5cd172f1bdc115addfefad60e139d61d021c9/component/desktopApp/src/jvmMain/kotlin/com/pablichj/incubator/uistate3/demo/DesktopAppNode.kt#L9

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2888">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
