### ISSUE TITLE
Can we integrate JxBrowser's web solution and provide relevant examples？

### ISSUE THREAD

**Issue by wangzhigang1112** [JetBrains/compose-multiplatform#3185]
Can we integrate JxBrowser's web solution and provide relevant examples？

**Comment by vlad-lubenskyi** [comment]
It's better to address this question to JxBrowser directly since it's a commercial library. Luckily, I work for JxBrowser :) 

JxBrowser provides a Swing component, and from what we know from our customers, it works pretty well. We have an experimental implementation of the Compose component but didn't see enough attention to finish it. 

We published our code on GitHub, you can find it useful: https://github.com/TeamDev-IP/Compose-BrowserView

**Comment by wangzhigang1112** [comment]
Thanks,I have found it.Is there a free solution?

**Comment by vlad-lubenskyi** [comment]
JxBrowser is not free. Did you look at a JCEF example made by Compose team? Here it is: https://github.com/JetBrains/compose-multiplatform/tree/dab4531fe4ffe8509ac4ce7a7336f1016960d67c/experimental/cef

**Comment by wangzhigang1112** [comment]
Are there any other free solutions? JCEF here doesn't seem to support MAC OS X

**Comment by vlad-lubenskyi** [comment]
In that case, I would recommend using the regular JCEF component. Since it uses Swing, the integration should be more or less smoothness. 

https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Swing_Integration/README.md

**Comment by ionull** [comment]
> Are there any other free solutions? JCEF here doesn't seem to support MAC OS X

JavaFx WebView does support macOS but it has bug that it crashes when using the Chinese Input Method.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3185">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.

**Comment by vlad-lubenskyi** [comment]
@wangzhigang1112 JxBrowser now supports Compose Desktop. This is still a work in progress, but we plan to finish it very soon. I don't want to advertise any links in the public repo, so write us if you want to try it.
