### ISSUE TITLE
LazyVerticalGrid get current y-position

### ISSUE THREAD

**Issue by SWRHARD** [JetBrains/compose-multiplatform#3192]
**using Compose Desktop**

I'm trying to make collapsing data and paging, when start to scrolling LazyVerticalGrid, but cant find any callback for get current y-position and last visible item, can u add this or may be u have another solution. Thanks!

**Comment by m-sasha** [comment]
The y position is not available because it's simply not defined for lazy lists. Imagine you have a million-item lazy list and you ask to scroll it to show the 100,000-th item. The list can't know the y position of that without instantiating and measuring 100,000 items (which would kill its performance).

As for the last visible item, you have `LazyGridState.layoutInfo.visibleItemsInfo`.

Also, in the future please such questions to either our slack, or stackoverflow.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3192">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
