### ISSUE TITLE
Missing SearchBar composable for desktop

### ISSUE THREAD

**Issue by denchic45** [JetBrains/compose-multiplatform#3227]

**Comment by eymar** [comment]
Do you mean a SearchBar from material3? https://www.composables.com/components/material3/searchbar

That's true. It should appear in Compose Mutlipatform material3 lib in the next major release if Jetpack Compose material3 1.2.0 goes stable (we don't base our releases on unstable JC releases).

**Comment by iadcialim** [comment]
@eymar Is there a site we can check the current versions of Compose Mutlipatform material3?

**Comment by AfricanBongo** [comment]
@iadcialim (even though you didn't ask me specifically lol) you can check on the releases tab of the repo, under the "Dependencies" heading:
https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.4.1

Illustration:
![Screenshot 2023-07-10 at 19 40 58](https://github.com/JetBrains/compose-multiplatform/assets/63804665/6a1286e2-032d-4fd4-8135-16240fb11f32)



Otherwise there is no other site I personally know of.

**Comment by iadcialim** [comment]
@AfricanBongo i appreciate it. thanks

**Comment by Zenturas** [comment]
Somehow it didn't get included in the most recent release that supports Material3 version 1.1.1. What is the reason for its exclusion?

**Comment by rustamsmax** [comment]
<img width="690" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/36570577/e50a4875-2017-494d-b39e-5e9d12375637">

**Comment by igordmn** [comment]
It should be available in 1.5.10-beta01

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3227">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
