### ISSUE TITLE
There are non-generic codes in the "common" section.

### ISSUE THREAD

**Issue by wwalkingg** [JetBrains/compose-multiplatform#3234]
**Describe the bug**
The code accessible in the "common" section should be code that is supported on any platform. However, there are currently many non-cross-platform codes, which has made me feel confused during development.
![image](https://github.com/JetBrains/compose-multiplatform/assets/42681996/a27bcdb4-5442-4f39-b44a-a3a89169ee56)
Window is desktop only,
asComposeImageBitmap not found in android,
and so on.

**Affected platforms**
Select one of the platforms below:
- All
- Desktop
- Web (K/Wasm) - Canvas based API
- Web (K/JS) - Canvas based API
- Web (K/JS) - HTML library
- iOS
- Other

**Versions**
- Kotlin version*: 1.8.20
- Compose Multiplatform version*: 1.4.0
- OS version(s)* (required for Desktop and iOS issues): Window11
- OS architecture (x86 or arm64): x86 
- JDK (for desktop issues): 17

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by wwalkingg** [comment]
Swing API can be found in common, i think it is not reasonable, or compose team has other factors to consider.

**Comment by eymar** [comment]
This issue is concerning Kotlin Multiplatform in general, not only compose.
One can write a platform-specific code in commonMain if, for example, all actual targets support that particlar API (like `asComposeImageBitmap` is supported by all except android as you mentioned).
If I have only a desktop target, than I can use any JVM specific API in commonMain.
If later I add js or ios targets, the commonMain won't work for them. Currently it's up to a developer to be careful when using platform-specific APIs (I absolutely agree that it's inconvenient).

But here is an issue you can track - https://youtrack.jetbrains.com/issue/KT-33578/Provide-an-ability-to-extend-the-set-of-platforms-that-the-source-set-is-analyzed-for-helping-project-future-evolution#focus=Comments-27-6383391.0-0

**Comment by wwalkingg** [comment]
> This issue is concerning Kotlin Multiplatform in general, not only compose.
> 
> One can write a platform-specific code in commonMain if, for example, all actual targets support that particlar API (like `asComposeImageBitmap` is supported by all except android as you mentioned).
> 
> If I have only a desktop target, than I can use any JVM specific API in commonMain.
> 
> If later I add js or ios targets, the commonMain won't work for them. Currently it's up to a developer to be careful when using platform-specific APIs (I absolutely agree that it's inconvenient).
> 
> 
> 
> But here is an issue you can track - https://youtrack.jetbrains.com/issue/KT-33578/Provide-an-ability-to-extend-the-set-of-platforms-that-the-source-set-is-analyzed-for-helping-project-future-evolution#focus=Comments-27-6383391.0-0 

Thanks

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3234">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
