### ISSUE TITLE
Unexpected change in 3D transforms

### ISSUE THREAD

**Issue by mipastgt** [JetBrains/compose-multiplatform#3307]
**Describe the bug**
Going from Compose-Desktop 1.4.0 to 1.4.1 the handling of 3D transforms has changed. The attached test program just rotates a rectangle around the x-axis. In 1.4.0 this resulted in some perspective transform but in 1.4.1 this looks like a parallel transform (infinite camera distance). Is this change in behaviour correct? See the attachments for details.

**Affected platforms**
- Tested on Desktop

**Versions**
- Kotlin version*:  1.8.20
- Compose Multiplatform version*: 1.4.0 and 1.4.1
- OS version(s)* (required for Desktop and iOS issues): macOS 13.4.1
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): temurin 17

**To Reproduce**
See Main.kt

**Expected behavior**
A perspective transform like in "Compose 1.4.0.png"

**Screenshots**
See attachments.

[Archiv.zip](https://github.com/JetBrains/compose-multiplatform/files/11929363/Archiv.zip)

**Comment by alexzhirkevich** [comment]
This change was made due to #3230

**Comment by mipastgt** [comment]
Yes, but that's about some specific problems with pointer input and not about changing the whole transformation behaviour.

**Comment by MatkovIvan** [comment]
> Is this change in behaviour correct?

Yes. Since you're applying custom matrix instead of built-in rotation, you control transformations (including perspective) yourself.
The root cause of it is that in 1.4.0, perspective was mistakenly applied unconditionally that lead to double/triple effect on complex UI trees. Current behaviour is applying `cameraDistance` only if `rotationX` or`rotationY` != 0. It matches common sense and Jetpack Compose (Android) behaviour.

Also please note that your sample crashes on android with `java.lang.IllegalArgumentException: Android does not support arbitrary transforms`

> that's about some specific problems with pointer input and not about changing the whole transformation behaviour.

Not exactly - input was just and symptom that transform matrixes were incorrect.

> The factor 72 between these two definitions would explain the discrepancy.

Well, during work on it I had the same question, but I'm sure that the current behaviour is correct and matches Google's Jetpack Compsoe android library. But there is some documentation mess about what units are used here.
This is my findings:
Because on Android there is additional layer between compose and skia, the specific code inside compose might look the different. Even more - on multi platform compose builds matrix itself instead of relying on skia camera etc.
The full chain for Android that explains this `cameraDistance * 72f` formula:

1. In `GraphicsLayerScope.cameraDistance`, it's "The distance is expressed in pixels" ([ref](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/graphics/GraphicsLayerScope.kt;l=158))
1. In `ViewLayer.cameraDistancePx`, it mentions that android's `View` "operates in Dp values" and it multiplies "pixels" to DPI ([ref](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/androidMain/kotlin/androidx/compose/ui/platform/ViewLayer.android.kt;l=115)). Please note that it's not "device-independent pixels" as you can expect.
1. In `View.setCameraDistance`, it's "The distance in "depth pixels"" ([ref](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/view/View.java;l=17386)). For passing value further, it divides value on DPI to get initial value back.
1. In `RenderNode.setCameraDistance`, it's again "The distance is expressed in pixels" ([ref](https://cs.android.com/android/platform/superproject/+/refs/heads/master:frameworks/base/graphics/java/android/graphics/RenderNode.java;l=1303)). It passes the value [as-is](https://cs.android.com/android/platform/superproject/+/refs/heads/master:frameworks/base/libs/hwui/RenderProperties.h;l=356) to skia.
1. In skia's `Sk3DView::setCameraLocation` , the code uses the camera distance as inches and multiplies it to const `72` to get "pt". ([ref](https://cs.android.com/android/platform/superproject/+/refs/heads/master:external/skia/src/utils/SkCamera.cpp;l=181))


Hope I answered to all your questions. Let me know if not

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3307">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
