### ISSUE TITLE
material3. Support mouse for `PlainTooltipBox`/`RichTooltipBox`

### ISSUE THREAD

**Issue by igordmn** [JetBrains/compose-multiplatform#3539]
Compose 1.5.0-rc01

```
@Composable
fun PlainTooltipSample() {
    PlainTooltipBox(
        tooltip = { Text("Add to favorites") }
    ) {
        IconButton(
            onClick = { /* Icon button's click event */ },
            modifier = Modifier.tooltipAnchor()
        ) {
            Icon(
                imageVector = Icons.Filled.Favorite,
                contentDescription = "Localized Description"
            )
        }
    }
}
```

It should appear on mouse hover, not on long click

**Comment by mnonnenmacher** [comment]
I tried to implement this behavior by using this code instead of `Modifier.tooltipAnchor()`:

```kotlin
modifier = Modifier.onPointerEvent(PointerEventType.Enter) {
  scope.launch {
    tooltipState.show()
  }
}.onPointerEvent(PointerEventType.Exit) {
  scope.launch {
    tooltipState.dismiss()
  }
}
```

This does not work as expected, because the tooltip automatically disappears after 1.5 seconds. For `PlainTooltipBox` there is no way around it. For `RichTooltipBox` this can be prevented by providing an `action`, but this adds additional space at the bottom of the tooltip which is not desired. Also, it seems that in Jetpack Compose there is a `rememberRichTooltipState(isPersistent: Boolean)` function where persistence can be configured but it is missing in Compose Multiplatform.

**Comment by alexzhirkevich** [comment]
This components were deprecated in upstream and their replacement already supports mouse hover

**Comment by igordmn** [comment]
Thanks! We'll check it after 1.6 merge

**Comment by igordmn** [comment]
Related issue:
https://github.com/JetBrains/compose-multiplatform/issues/4275
