### ISSUE TITLE
Being able to use sel_registerName without export dependency to binaries

### ISSUE THREAD

**Issue by MohamedRejeb** [JetBrains/compose-multiplatform#3549]
Let's say that we have two KMP modules, A and B. B is using A and B is used in the iOS app.
iOS -> B -> A

If I'm using `sel_registerName` in B, everything works fine. But when I use it in A, I get an error. And to get rid of the error, I have to export A to binaries.

I don't need to export the dependency to binaries since I'm not going to use any code from the Obj-C/Swift. Also, exporting is going to increase the size of the iOS app.

I can stick with using `sel_registerName` in B but it's not the case for libraries or multi-module projects.

Thanks!

**Comment by Walingar** [comment]
Hello @MohamedRejeb, thank you for the issue and sorry for the late reply!

Described issue is related to Kotlin Multiplatform/Native rather than Compose Multiplatform, so can you please create an issue in [Kotlin Multiplatform bug tracker](https://youtrack.jetbrains.com/newIssue?project=KT&c=Subsystems%20Native) in YouTrack

Thank you!

**Comment by MohamedRejeb** [comment]
Hi @Walingar , you are right. Thanks!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3549">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
