### ISSUE TITLE
Compose Multiplatform should warn when CADisableMinimumFrameDurationOnPhone is not configured properly

### ISSUE THREAD

**Issue by SebastianAigner** [JetBrains/compose-multiplatform#3634]
**Describe the bug**
Projects created with our mobile template before [this commit](https://github.com/JetBrains/compose-multiplatform-ios-android-template/commit/87dfc98d367525942dbd032c396c7c5c3c5d0993) – or without our template – don't specify the correct value for `CADisableMinimumFrameDurationOnPhone` by default. This results in visibly degraded performance on high-refresh-rate displays, because it locks the UI to 60fps.

Compose should warn the user on app startup if this setting is misconfigured. Such a warning would hopefully help prevent folks accidentally publishing Compose Multiplatform apps that have degraded visual performance.

**Affected platforms**
- iOS

**Versions**
- Compose Multiplatform version*: 1.5

**Comment by igordmn** [comment]
Sounds reasonable.

We probably should check it in [Runtime](https://stackoverflow.com/questions/9530075/ios-access-app-info-plist-variables-in-code), because we not always have access to plist at compile time (in case if Compose added to the existing applciation without using our Gradle plugin in the app module)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3634">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
