### ISSUE TITLE
Use Gson with release package (enabled proguard)

### ISSUE THREAD

**Issue by SudoDios** [JetBrains/compose-multiplatform#3755]
**Describe the bug**
I use gson in my project. Everything works fine until i release package & get this error :
`Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
	at proguard.optimize.gson._GsonUtil.<clinit>(_GsonUtil.java:45)`

**Affected platforms**
Select one of the platforms below:
- Desktop

**Versions**
- Kotlin version*: 1.9.10
- Compose Multiplatform version*: 1.5.1
- OS version(s)* (required for Desktop and iOS issues): Ubuntu 20.04.6 LTS
- OS architecture (x86 or arm64): 64-bit
- JDK (for desktop issues): openjdk-18

**Comment by eymar** [comment]
I see you've already asked about this issue here - https://github.com/google/gson/issues/2503 

You can try to change the Proguard version:
https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials/Native_distributions_and_local_execution#minification--obfuscation

```kotlin
compose.desktop {
    application {
        buildTypes.release.proguard {
            version.set("7.4.0-beta02")
        }
    }
}
```

We'll swtich to 7.4.0 by default when it's stable.

**Comment by SudoDios** [comment]
Yes.
My problem is solved.
Sorry, I didn't care to close the issue
thank you ❤️.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3755">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
