### ISSUE TITLE
[desktop] Copy image into clipboard and paste it back

### ISSUE THREAD

**Issue by avently** [JetBrains/compose-multiplatform#3763]
For now there is no way to copy and paste image to/from clipboard. In some scenarious it's useful, for example, when you want to copy image from browser and paste it for sending within the app. 
Let me know if I should create the issue in skiko repo because it looks like you use skiko implementation on desktop.

**Comment by pjBooms** [comment]
It is a nice enhancement. No need to create the issue in skiko. I would rather create the issue in Jetpack Compose issue tracker to extend Clipboard manager interface. Because, we would hardly implement this feature in Desktop only scenario

**Comment by anakiK1to** [comment]
Hello, any updates obut this feature? Its seems to be very usefull 
Or maybe somebody csn suggerst some workarounds to copy/paste images?

**Comment by dima-avdeev-jb** [comment]
You can do it with standart JVM features.
Please take a look at this project: https://github.com/avdim/compose-vector/blob/e507f6946d389e8e320b8db736319d783596516f/lib/src/jvmMain/kotlin/lib/vector/EditMode.kt#L139

**Comment by hakanai** [comment]
I think there is some scope for Compose to come up with a better API for this.

My issues with the AWT clipboard API:
- No way to listen for changes to the content (there is a listener to listen for changes to the available flavors, but that doesn't help you if the user copies multiple images in a row!)
- Because of that, you have to poll at some interval to detect changes (performance and energy cost)
- `getContents` returns a new object every time even when it is the same contents - and also does not support `equals`/`hashCode`, making it impossible to trivially check whether it's the same data as last call
- Even the `Image` you get out of it is a different object each time - meaning you have to resort to pixel by pixel comparison of the images.

End result: an expensive image comparison routine which has to be called frequently due to the lack of a listener.

Meanwhile, the native API for clipboard on Windows, at least, does have a way to listen for changes.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3763">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
