### ISSUE TITLE
Camera issue in webview iOS

### ISSUE THREAD

**Issue by ssvaghasiya** [JetBrains/compose-multiplatform#3791]
When i open camera and close camera in webview webview close automatically

example video:
https://github.com/JetBrains/compose-multiplatform/assets/49331161/2ef4381a-c8cb-46ff-a552-42269ed37aec

**Comment by elijah-semyonov** [comment]
Could you be more specific about what you struggle to figure out in particular?

**Comment by elijah-semyonov** [comment]
It goes back, because ComposeScene is destroyed, and hence interop view is also destroyed.
In order for web view not to get destroyed, you could present a native `UIViewController` with that web view and wire in the callbacks.

Have a look at this code to have a better idea how to do it.
https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/mpp/demo/src/uikitMain/kotlin/NativePopupExample.kt

**Comment by elijah-semyonov** [comment]
Because the web view was erroneously still in the uikit hierarchy, which was a bug of beta-01:
https://github.com/JetBrains/compose-multiplatform/issues/3749

**Comment by savan-ixfi** [comment]
Hello @elijah-semyonov please provide solution for above code

**Comment by elijah-semyonov** [comment]
I suggested a solution and an example in https://github.com/JetBrains/compose-multiplatform/issues/3791#issuecomment-1753038883 .
It's up to you to figure it out. If it's still not clear, discuss it with fellow community members in the Kotlin Slack.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-3791">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
