### ISSUE TITLE
[Feature] Make string resources accessible synchronously

### ISSUE THREAD

**Issue by rustamsmax** [JetBrains/compose-multiplatform#4349]
Now strings are stored in xml files and are loaded via LaunchedEffect (or suspend fun) asynchronously
Loading strings asynchronously is not a good choice as it can be read inside non asynchronous functions.
We could make them accessible synchronously creating string holder classes on compile time.

For example:
```
<resources>
 //basic strings
 <string name="label_dashboard">Лента</string>
 <string name="label_menu">Меню</string>
 <string name="label_menu_account">Профиль</string>
 
 //strings with args
 <string name="label_count_total">Всего: %1$d</string>
 <string name="label_time_past_hour">%1$d чс.</string>
 
</resources>
```

```
interface Strings {

  fun label_dashboard(): String
  fun label_menu(): String
  fun label_menu_account(): String

  fun label_count_total(arg: Float): String
  fun label_time_past_hour(arg: Float): String

}

class StringsRu: Strings {
  override fun label_dashboard(): String = "Лента"
  override fun label_menu(): String = "Меню"
  override fun label_menu_account(): String = "Профиль"

  override fun label_count_total(arg: Float): String = "Всего: ${arg}"
  override fun label_time_past_hour(arg: Float): String = "${arg} чс"
}
```

**Comment by rustamsmax** [comment]
And for English
```
class StringsEn: Strings {
  override fun label_dashboard(): String = "Dashboard"
  override fun label_menu(): String = "Menu"
  override fun label_menu_account(): String = "Account"

  override fun label_count_total(arg: Float): String = "Total: ${arg}"
  override fun label_time_past_hour(arg: Float): String = "${arg} hr"
}
```

Environment variable holds instance of a Strings (StringsRu, StringsEn)
And we can read them anywhere

**Comment by LionZXY** [comment]
Right now, you have a choice: 
1) Either load resources asynchronously via the `suspend` function
2) Either load resources synchronously via the `runBlocking` function

You have a synchronous and asynchronous way of loading. 

The proposed solution is only the synchronous way of loading. These strings don't come from nowhere, they are loaded into RAM from the disc and slow down the program execution by slowing down the first frame display time. In terms of features, the current resource API is superior to the proposed solution and offers developers the choice of

**Comment by pablichjenkov** [comment]
But isn't runBlocking{} not recommended to use? I actually tried it in a production App and had to remove it because crashes related to thread being used in a parked state or sort of.

**Comment by xiaozhikang0916** [comment]
Up for string resources as class fields.

Another benefit is that string template args can be very clear for user as function parameters to avoid misused like missing or wrong type.

**Comment by dima-avdeev-jb** [comment]
@terrakok Can you please help with answer after your vacation?

**Comment by terrakok** [comment]
The library supports all targets. It means a Browser as well. But browser targets have a limitation: not to block anything.
We will discuss a subset of blocking API for non-browser targets.

To have text resources as a code is not good idea because it increases binary size (what maybe critical for start time in some cases). And it may lead to compilation problems when resources have a huge texts.

**Comment by rustamsmax** [comment]
If we store the strings in code all problems will be solved.
@terrakok Your concern about binary size can be solved via dynamic modules which is supported by both android/iOS

**Comment by terrakok** [comment]
Could you show how the "dynamic modules" helps here?
And a compile time and a binary size problems are not solved yet.

**Comment by terrakok** [comment]
The moko uses platform's resources to provide an API with them for a platform specific code. We don't need it. The compose multiplatform resources library is designed for compose multiplatform applications.

General answer for the issue is: string resources are not regular strings in your code. It is more high level thing. If you need to use it in you data layer (non a compose context) you are suppose to use resource IDs instead. And convert them into actual strings on the presentation layer only. The same approach as for icons.

```kotlin
data class Parcel(
  val icon: DrawableResource,
  val label: StringResource
)
```

Because actual values depend on user's environment which may be changed dynamically

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4349">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
