### ISSUE TITLE
How to use Dialog with AnimatedVisibility

### ISSUE THREAD

**Issue by LazyIonEs** [JetBrains/compose-multiplatform#4431]
How to use `Dialog` with `AnimatedVisibility`, or how to animate the display or exit of `Dialog`

**Comment by igordmn** [comment]
This is only possible if you use `AnimatedVisibility` inside `Dialog`. Because its content is drawn outside of the current node, usual modifiers don't work with it.

See [the tutorial for Android](https://www.sinasamaki.com/custom-dialog-animation-in-jetpack-compose/) ([code](https://gist.github.com/sinasamaki/daa825d96235a18822177a2b1b323f49?ref=sinasamaki.com)). The only difference with other platforms is that you need to configure native dialog differently:
- you need to override scrimColor:
```
        Dialog(
            onDismissRequest = onDismissRequest,
            properties = DialogProperties(
                usePlatformDefaultWidth = false,
                scrimColor = Color.Transparent
            )
        )
```
- you don't need to configure `dialogWindow`

Also, it is not possible to use it with opinionated popups/dialogs such as DropdownMenu/AlertDialogs. The only way to animate them is to copy and change the implementation.

**Comment by MatkovIvan** [comment]
Related to #4365

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4431">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
