### ISSUE TITLE
`Material3.PullToRefresh()` doesn't work with mouse

### ISSUE THREAD

**Issue by wen-flower** [JetBrains/compose-multiplatform#4436]
**Describe the bug**
Version 1.6.0, cannot be refreshed using Material3.PullToRefresh()

**Affected platforms**
- Desktop

**Versions**
- Kotlin version*: 1.9.22
- Compose Multiplatform version*: 1.6.0
- OS version(s)* : Win11
- OS architecture (x86 or arm64): x86
- JDK (for desktop issues): JDK 17

**Additional context**
[Desktop: Nested scrolling is not working properly #653](https://github.com/JetBrains/compose-multiplatform/issues/653)
[https://developer.android.com/reference/kotlin/androidx/compose/material3/pulltorefresh/package-summary](https://developer.android.com/reference/kotlin/androidx/compose/material3/pulltorefresh/package-summary)

**Comment by MatkovIvan** [comment]
It doesn't seem that linked #653 issue or 1.6.0 is really related. #653 is not included to 1.6.0, but even with this fix it will not trigger this logic because it [explicitly waits dragging](https://github.com/JetBrains/compose-multiplatform-core/blob/v1.6.0/compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/pulltorefresh/PullToRefresh.kt#L333-L334), but `scrollable` modifier [disables](https://github.com/JetBrains/compose-multiplatform-core/blob/v1.6.0/compose/foundation/foundation/src/commonMain/kotlin/androidx/compose/foundation/gestures/Scrollable.kt#L657) dragging for mouse.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4436">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
