### ISSUE TITLE
Is it possible to use Mesa 3D Graphics Library to support OPENGL?

### ISSUE THREAD

**Issue by RafaelAthosPrime** [JetBrains/compose-multiplatform#4459]
is it possible to use the skiko.renderApi OPENGL with Mesa3D OpenGL implementation? https://www.mesa3d.org/

I have been having performance problems with jetpack compose on the desktop with customers that do not have an integrated video card and do not support OPENGL, I have tried using renderApi SOFTWARE_FAST but the performance is terrible dropping to 5~10FPS when used on a screen with resolution 1920x1080

I've seen some videos of people using Mesa3D to open Blender3D on computers that don't have an integrated video card. Is it possible to use this in a desktop project with Compose to support the OPENGL without a fallback to SOFTWARE?

Kotlin Version: 1.9.22
Compose Version: 1.6.0
OS: Windows 10

**Comment by igordmn** [comment]
Compose should fallbacks to SOFTWARE_FAST automatically if it can't use OPENGL. Not sure how MESA can help in the case of non-existed GPU, because it also renders on CPU.

If MESA could help, MESA should be installed on the user machine. I can't provide any guides for that, but if MESA implements OpenGL API, there shouldn't be any issues.

For improving Software renderer, let's keep https://github.com/JetBrains/compose-multiplatform/issues/4199.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4459">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
