### ISSUE TITLE
ScrollBar changes it's track size when scrolling in LazyColumn with items with different height

### ISSUE THREAD

**Issue by avently** [JetBrains/compose-multiplatform#4540]
**Describe the bug**
LazyColumn with items varying in height makes scrollBar changing its track height while scrolling up/down.
Please, take a look at screenrecord for better understanding of the problem.
It's probably impossible to know actual LazyColumn content height without composing all items but maybe there is a way to do it that doesn't affect performance too much. Do you have any idea how to do it and to get constant scrollbar height in the same list of items while scrolling up/down? 

**Affected platforms**
- Desktop (Windows, Linux, macOS)

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): 
- OS architecture (x86 or arm64): x86

**To Reproduce**
Repeat the same as on a video: just create a bunch of items with different height and place them into LazyColumn.

**Expected behavior**
Ideally, it should know sizes of items without displaying them. 

**Screenrecord**

https://github.com/JetBrains/compose-multiplatform/assets/7953703/3dbf1b1a-1dfe-4fda-9e1e-e86ba3baf693

**Comment by m-sasha** [comment]
This is the expected behavior, by design. As you mentioned, the scrollbar has no way of knowing the size of items that are not currently composed, so it has a heuristic based on the currently composed ones. This heuristic can be inaccurate when the sizes of the items vary significantly.

Trying to obtain the actual sizes of the items, however, would violate the basic purpose of lazy layouts.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4540">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
