### ISSUE TITLE
[Question] Will there be a similar equivalent  androidx.lifecycle:lifecycle-viewmodel  implemented before Compose for iOS to Beta?

### ISSUE THREAD

**Issue by xinzhengzhang** [JetBrains/compose-multiplatform#4545]
There is the [roadmap](https://blog.jetbrains.com/kotlin/2023/11/kotlin-multiplatform-development-roadmap-for-2024/) list that` Make all Jetpack Compose core APIs and components multiplatform.`  I want to know which components are expected to be implemented on compose for iOS.

Especially about Lifecycle and ViewModel.
Since UIKit does not have very good lifecycle distribution capabilities, it is relatively painful to implement on iOS systems. At the same time, MVVM is also a mainstream UI implementation method. I would like to know what Compose-multiplatform's plan is for this piece?

**Comment by xinzhengzhang** [comment]
Although the ViewModel, ViewModelStore, etc. are cross-platform, there is no intermediate layer between the iOS View and ViewModel, such as getting iOS association to the iOS lifecycle ViewModel in the Compose world through [Mediator](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/scene/ComposeSceneMediator.uikit.kt)

**Comment by xiaozhikang0916** [comment]
Would like to have a lifecycle-awared view model store rather than [current one](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/lifecycle/lifecycle-viewmodel-compose/src/jbMain/kotlin/androidx/lifecycle/viewmodel/compose/LocalViewModelStoreOwner.jb.kt#L24).

It can get benefit from ARC of object-c to call `ViewModelStore.clear()` when a controller is nolonger needed.

**Comment by MatkovIvan** [comment]
> I would like to know what Compose-multiplatform's plan is for this piece?

The initial version should be already available in the latest dev build

> we look forward to Navigation becoming multi-platform as soon as possible.

The initial version should be already available in the latest dev build too

> getting iOS association to the iOS lifecycle ViewModel in the Compose world through [Mediator](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/ui/ui/src/uikitMain/kotlin/androidx/compose/ui/scene/ComposeSceneMediator.uikit.kt)

Yes, it's how Compose provides it for its content

> Would like to have a lifecycle-awared view model store rather than [current one](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/lifecycle/lifecycle-viewmodel-compose/src/jbMain/kotlin/androidx/lifecycle/viewmodel/compose/LocalViewModelStoreOwner.jb.kt#L24).

Mentioned implementation is just default one, it might be overridden by composition local (navigation library should override lifecycle and VM storage). Since we have nothing that we control above Compose the only alternative for is throwing the error by default and require explicit initialization. We cannot do anything with in in compose itself because we're not going to add viewmodel to dependencies to Compose. Please note that it's subject to change, not having "global"/any storage by default is a good candidate.

> It can get benefit from ARC of object-c

Good theory, but it won't work due to captured references in kotlin runtime/GC itself. @elijah-semyonov is an expert here


Closing, as I replied to initial question.

**Comment by Ribesg** [comment]
> > we look forward to Navigation becoming multi-platform as soon as possible.
> 
> The initial version should be already available in the latest dev build too

This does not seem right https://issuetracker.google.com/issues/281774647

**Comment by MatkovIvan** [comment]
@Ribesg we're not going to upstream KMP navigation to Google's AOSP repo

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4545">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
