### ISSUE TITLE
Make resize area larger or configurable for undecorated windows

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#4574]
When making a window undecorated, the area that you can click in the corners on macOS is sigificantly smaller than when the window is decorated. This leads to frustration as you are tying to get the mouse into the tiny little area that allows you to click and drag to resize an undecorated window.

I would like to make this area larger. I am not sure if this is more on the compose side or the swing side.

Platform: Desktop
OS: macos 14.4.1 arm64
Compose Version: 1.6.1
Kotlin version: 2.0.0-Beta5

* note that an undecorated window also shows different icons when resizing compared to a decorated window, at least on my platform

**Comment by m-sasha** [comment]
We'll consider it.

In the meanwhile, take a look at [UndecoratedWindowResizer](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/window/UndecoratedWindowResizer.desktop.kt).

You could:
1. Make the (Compose) Window unresizable
2. Make the (Swing) Window resizable
3. Copy `UndecoratedWindowResizer` into your code and add it to the content of the window at the top level.

**Comment by m-sasha** [comment]
> I wanted to call window.setResizable in such a way to only set the swing part resizable, but not the compose part. This was difficult because ComposeWindow overrides setResizable:

Yes, that's unfortunate. We could avoid overriding `setResizable` in `ComposeWindow`. @MatkovIvan ?


> I had to call Modifier.layoutId with the exact right string. Searching the compose code base I realized this string had some affect somewhere, so I had to keep it the same.

You didn't have to do that. `Modifier.layoutId` is a way to tag children elements so that the `MeasurePolicy` of the layout can identify them. In this case, the Layout in `WindowContentLayout` identifies it and has separate code to size and position it. In your case, you aren't putting your resizer in `WindowContentLayout`, so it meaningless.

I'm not sure we want to expose the resizer itself, but we'll see whether we can provide a smaller API surface to just define the border thickness. Or maybe we just need to select a better default value. Maybe check the sizes of the resizable areas of native windows and use that. @igordmn ?

**Comment by m-sasha** [comment]
If you put your resizer immediately in the window, as the last element, then yes, it looks like `WindowContentLayout` will find it. But this is not guaranteed (in the sense that we could change this and not consider it a breaking change), and is more a bug than a feature.

I'd recommend not relying on this, and instead laying out your resizer by yourself (just put all your content in a `Box` and set `Modifier.matchParentSize` on the resizer).

**Comment by m-sasha** [comment]
Hmm, now that I think about it - do you actually need to make the AWT window resizable? The resizability there is "by the user". You can just call `ComposeWindow.resizable = false` and that's it.

**Comment by m-sasha** [comment]
Window.setResizable is useful for decorated windows.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4574">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
