### ISSUE TITLE
Compose Multiplatform support for Mac OS native apps

### ISSUE THREAD

**Issue by alexstyl** [JetBrains/compose-multiplatform#4580]
Are we ever going to see Mac being supported as a target for Compose Multiplatform similar to iOS native apps?

I am already using Compose on JVM and it's great, however it doesn't give me the flexibility I want to support native features

**Comment by elijah-semyonov** [comment]
Hi, we don't have plans for supporting macOS native target currently. What kind of restrictions does JVM impose in your case?

**Comment by alexstyl** [comment]
Would love to be able to add a Share extension to my Mac OS app. This is something I haven't figured out how to do exactly using a JVM app. 

The only related resource I have found online on how to do this is this stack overflow answer on [how to add a share extension to an electron app](https://stackoverflow.com/a/76420958). Looking at this makes me think that if I attempt this I will spend days on hacks instead and maybe I will be able to it, instead of focusing on improving my product. As a solo founder this is a huge waste of time/resources, so I would rather not try.

**Comment by luca992** [comment]
There is already native macos support, it's pretty buggy though. Things like window resize and text input aren't working last time I checked

**Comment by elijah-semyonov** [comment]
Oh, no... It's an experimental target that we don't mention, don't give any guarantees about and it's constantly breaking. That's exclusively an internal sandbox and supporting one more platform (as opposed to just JVM environment) is far from trivial due to sheer amount of integrations to be done between specific platform and Compose core.

Considering the amount of work done on CMP for Desktop, just looking into the specific use cases like `alexstyl` has mentioned and finding out a solution for them is a more feasible approach.

**Comment by luca992** [comment]
@elijah-semyonov Despite all that... I think it runs more smoothly than jvm haha. Hopefully it gets official support eventually.

**Comment by alexstyl** [comment]
Closing this as @elijah-semyonov mentioned there are no plans to support Mac (at least publicly)

If I ever try to attempt the feature i described ill ask in the slack or open a new issue

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4580">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
