### ISSUE TITLE
Support `commonResources` to `R`/`Icon`

### ISSUE THREAD

**Issue by chrisjenx** [JetBrains/compose-multiplatform#4613]
Sorry if I missed it but trying to convert `Res` to `Icon` or `R.drawable` but couldn't see how. 

Right now I just copied into res/drawable in the android target.

Example use is Notifications:
```
.setSmallIcon(R.drawable.icon_logo_head)
```
Would be nice if we could do `Res.drawable.icon_logo_head.toIcon()` or similar.

Thanks!

**Comment by terrakok** [comment]
It is not possible because the compose resources were designed for the compose only.
`setSmallIcon` API is the android system function. It won't work with compose multiplatform resources.
Workaround is to use platform specific resources for such cases:
 1) put your icon to the `androidMain/res/drawable`
 2) add the `res` dir as android resources dir
```kotlin
android {
  sourceSets["main"].apply {
    manifest.srcFile("src/androidMain/AndroidManifest.xml")
    res.srcDirs("src/androidMain/res")
  }
}
```
 3) use it as a regular android resource in the android source set

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4613">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
