### ISSUE TITLE
Support Kotlin 1.9.24

### ISSUE THREAD

**Issue by hoc081098** [JetBrains/compose-multiplatform#4769]
```
Compose Multiplatform 1.6.10-rc01 doesn't support Kotlin 1.9.24. Please see https://github.com/JetBrains/compose-jb/blob/master/VERSIONING.md#kotlin-compatibility to know the latest supported version of Kotlin.
```

**Comment by eygraber** [comment]
There's a 1.5.13.1 compiler version that supports Kotlin 1.9.24

**Comment by hoc081098** [comment]
> There's a 1.5.13.1 compiler version that supports Kotlin 1.9.24

Thanks, I've just seen it 🙏

**Comment by torokati44** [comment]
> There's a 1.5.13.1 compiler version that supports Kotlin 1.9.24

Then why am I getting `Could not find androidx.compose.compiler:compiler:1.5.13.1.`? :thinking:
https://github.com/ruffle-rs/ruffle-android/actions/runs/9061466139/job/24893268331#step:6:71

**Comment by MatkovIvan** [comment]
> Then why am I getting Could not find androidx.compose.compiler:compiler:1.5.13.1.?

Because it's Google's compiler for Android, but not for multiplatform that mentioned above. Multiplatform/JetBrains one is `org.jetbrains.compose.compiler:compiler` (applied only for K1)

You can find it here
https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/compiler/compiler/1.5.13.2/
It will be available in maven central a bit later.

**Comment by torokati44** [comment]
Ah, I see, thank you! Sorry for my ignorance, I'm not familiar with the Kotlin ecosystem...

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4769">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
