### ISSUE TITLE
Consider removing `Unconfined` dispatcher as default `CoroutineContext` for `ComposeScene` creation

### ISSUE THREAD

**Issue by JakeWharton** [JetBrains/compose-multiplatform#4799]
I am standing up Compose UI on a new target, and was surprised to see `Dispatchers.Unconfined` as the default value for the `CoroutineContext` when setting up a Compose scene. This seems like a dangerous default. I did not initially supply this value and it caused deadlocks in my application.

**Comment by m-sasha** [comment]
I agree that it's a bad default value, but changing it could break someone's code (after recompilation).

On the other hand, it is really a bad value because:
1. It causes effects to be run immediately when they are launched, which changes the order relative to what happens normally.
2. When resuming, it resumes on an unspecified thread.

So maybe it's worth changing even it breaks someone's code.

P.S. We should also change this in tests, as I mentioned here: https://youtrack.jetbrains.com/issue/COMPOSE-1290/LaunchedEffect-run-in-composition-phase-in-tests

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4799">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
