### ISSUE TITLE
Make livedata available on Apple targets

### ISSUE THREAD

**Issue by Mats-Hjalmar** [JetBrains/compose-multiplatform#4955]
I have an App where we are using `MutableStateFlow` to share data to the UI. Problem is that we need to update the view when the same value is emitted on the flow.

**Comment by pablichjenkov** [comment]
Instead of a StateFlow use a SharedFlow with repeat 1. You will also have to update the Update Policy in your compose State, because compose State also don't Emit events on the same event. 
Bottom line you should change your design into something that represents your state not depending on this state updates.
That would be better for performance too.

**Comment by MatkovIvan** [comment]
Thanks @pablichjenkov for reply regarding the specific issue.

I'll just add regarding porting `LiveData` to multiplatform - there is no plan to do that. 
Obvious reasons are:
- `LiveData` is written on java
- There is `Flow` equivalent with all lifecycle bindings

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-4955">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
