### ISSUE TITLE
Deep Linking Support - iOS

### ISSUE THREAD

**Issue by Mohmd-H-BH** [JetBrains/compose-multiplatform#5003]
I am curious to know if there are any plans to add support for deep linking on iOS soon.

**Note:**
As I am in the process of developing my first application using Compose Multiplatform, having deep linking support available **ASAP** is essential. This feature is particularly important during the initial stages of development to ensure a smooth and efficient workflow.

**Comment by MatkovIvan** [comment]
It's not available in first alphas, but it's in our TODO list

**Comment by chrisjenx** [comment]
We use Decompose instead of the Navigation lib, but the deeplinking due to the way it works is a little bit different on each platform so you would need to do some of your own lift regardless of if you use jetpack or decompose etc

**Comment by Mohmd-H-BH** [comment]
> It's not available in first alphas on adopted Jetpack Navigation, but it's in our TODO list.
> 
> If the question is not about navigation library but just about "Compose Multiplatform" - platform APIs are available via KMP and Compose UI framework doesn't prevent usage of it. Also, there are a few 3rd party libraries to simplify the process

@MatkovIvan 
Appreciate your reply, I got your point 🙋‍♂️.

**Comment by Mohmd-H-BH** [comment]
> We use Decompose instead of the Navigation lib, but the deeplinking due to the way it works is a little bit different on each platform so you would need to do some of your own lift regardless of if you use jetpack or decompose etc

@chrisjenx 
Thank you for your interaction, you are right.

In fact, I have looked into Decompose and was impressed by its features, documentation, and developer engagement. However, I wonder if the support will remain at the same level when compared to the official libraries from JetBrains or Google.

**Comment by chrisjenx** [comment]
I think the same way people use a bunch of different libraries instead of Jetpack offerings (some people don't like the graph definition with Jetpack Nav) so at least for the near term I'm not worried. 
It also move's much quicker and it's easy for ourselves to form/modify over the jetpack lib which is at the whim of Google and CMP team pulling upstream changes.
Also it will probably see better integration with iOS/Web/Desktop, which I would take a guess is more lift than Google/Jetbrains could probably offer right now with the other huge backlog of things they need to add to CMP.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5003">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
