### ISSUE TITLE
(Select-All -> Delete) action in TextField doesn't work when empty text state disposes composition

### ISSUE THREAD

**Issue by mgroth0** [JetBrains/compose-multiplatform#5023]
**Describe the bug**

In a typical text field, selecting all of the text and pressing the delete key causes all of the text to be deleted.

However, if the text field is set to disapear if the text is empty then this will not work. The TextField flickers. For a brief moment it looks like the text is deleted but it comes right back.

Note that deleting all of the text one deleting one character at a time works fine with the same code.

**Affected platforms**
- Desktop (macOS)

**Versions**
- Libraries:
  - Compose Multiplatform version: 1.7.0-dev1686

- Kotlin version: 2.0.0-RC1
- OS version: MacOS 14.5
- OS architecture: arm64
- JDK:  20

**To Reproduce**
1. Run this code snippet:

```kt
import androidx.compose.material3.TextField
import androidx.compose.runtime.mutableStateOf
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

fun main() {
    val text = mutableStateOf("1. Select all of me\n2. Delete")
    application {
        Window(
            onCloseRequest = ::exitApplication
        ) {
            val textValue = text.value
            if (textValue.isNotEmpty()) {
                TextField(
                    value = textValue,
                    onValueChange = {
                        text.value = it
                    }
                )
            }
        }
    }
}

```
2. Click on the text
3. Use the Command-A keyboard shortcut to select all of the text
4. Press the Delete keyboard button
5. Observe the textfield flicker, but otherwise the text does not get deleted

**Expected behavior**

The text should be deleted, and the text field should disapear.

If you delete one character at a time, this behavior can be observed.

**Additional context**

The reason that my app has a text field like this is because some items can have optional text metadata. It makes sense in my UI because there is a separate way to "add" a text area with template text, but when all of the text gets deleted that is equivalent to the entire text element being deleted.

**Comment by m-sasha** [comment]
This behaves identically on Android. Please report it in the [AOSP Compose bug tracker](https://issuetracker.google.com/issues?q=status:open%20componentid:612128&s=created_time:desc).

**Comment by m-sasha** [comment]
The problem here appears to be due to a combination of unlucky conditions.

When the `TextField` is removed from the composition, the corresponding `FocusTargetNode` is detached, which calls `clearFocus`, which then deselects the text. The text selection is part of the (internal) `TextField` state, so when it changes, `onValueChange` is called again. But `TextField`'s internal state still has the previous text, so `onValueChange` ends up being called with the old value, resetting your `text`. You can work around this by setting a flag when the text becomes empty in `onValueChange` and not resetting it, i.e. `onValueChange = { if (it.isEmpty()) showTextField = false }

I'm guessing the answer from AOSP would be that it's an artifact of the design of the (old) `TextField`, and that you should upgrade to the new one (that takes a `TextFieldState`), where this issue doesn't exist.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5023">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
