### ISSUE TITLE
Error: self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by wucong1997** [JetBrains/compose-multiplatform#5082]
Hi, When compiling Kotlin native on Linux, run. /gradlew publish, the following error occurs: “self-signed certificate in certificate chain”. How to deal with this kind of problem?

![截图](https://github.com/JetBrains/compose-multiplatform/assets/37244241/c5e88ad3-48e4-40e2-b47f-72bff0a9a4d0)

**Comment by eymar** [comment]
The error message is not relevant for Kotlin/Native.
It looks like you jave a kotlin/js target too.
if you disable k/js target, this error shouldn't appear.

The error "Error: self-signed certificate in certificate chain" suggests that maybe there is a particular (intentional or not) configuration in your network. The connection might be not secure.

**Comment by wucong1997** [comment]
Thank you for your answer. How can I disable k/js target?

**Comment by eymar** [comment]
check your build.gradle or build.gradle.kts. There you can find somethine like:

```kotlin
js {
    browser()
    ....
}
```

Try to comment that block or remove it.

**Comment by eymar** [comment]
I hope that helped.  Closing this for now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5082">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
