### ISSUE TITLE
Make AnnotatedString.Companion.fromHtml available to multiplatform

### ISSUE THREAD

**Issue by hmy65** [JetBrains/compose-multiplatform#5093]
Currently, this function is not implemented. Maybe make it available in the future. This library “com.mohamedrejeb.richeditor” did it, but we want official support.

```
actual fun AnnotatedString.Companion.fromHtml(
    htmlString: String,
    linkStyles: TextLinkStyles?,
    linkInteractionListener: LinkInteractionListener?
): AnnotatedString {
    throw UnsupportedOperationException("Compose Multiplatform doesn't support fromHtml")
}
```

**Comment by MatkovIvan** [comment]
We're not planning to support this helper in the next version. It was removed from common and now it's android-only, see https://android-review.googlesource.com/c/platform/frameworks/support/+/3150316

Also, it's questionable to add this in the core ui module because it requires extra dependencies for parsing that will increase binary size for all Compose applications.

The current recommendation here is to use 3rd party solutions

**Comment by hmy65** [comment]
@MatkovIvan Fine, for anyone who have same request by do not wanna third party lib, I implemented myself by recursing the source string to find html tags, then adding spanstyle to each tag. 
Let's close this issue for now, but maybe reopen in the future.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5093">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
