### ISSUE TITLE
IDEA Preview Plugin: Support Compose Web

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-multiplatform#747]
The preview IDEA plugin is still in alpha, but supporting Compose Web would be nice too.

1. Provide a @Preview annotation in `web`
2. Add this FQ annotation class in the IDEA plugin

**Comment by avently** [comment]
Do you have this plugin working in IDEA? I can't make it working. Is there any instruction or something?

**Comment by akurasov** [comment]
@avently it works since 0.5.0-build235. See https://github.com/JetBrains/compose-jb/issues/865

**Comment by avently** [comment]
@akurasov already used it. Cool but it's on early stages, so will wait more time

**Comment by akurasov** [comment]
@avently 
what is missing there from your perspective?

**Comment by avently** [comment]
@akurasov i tried the plugin a week ago or two and it hadn't feature to update the view. I mean when i clicked gutter icon to run the preview it worked only for the first time but after that the preview still shows an image from the first launch regardless of how many times i rerun it. Also it couldn't show complex scene instead of one `Text(...)`. So it wasn't ready and i decided to wait.

**Comment by waveduke** [comment]
Do you have any idea when this will be available for compose web?

**Comment by Burtan** [comment]
Would be very useful on web as well.
