### ISSUE TITLE
TaskBar icon scaling poorly

### ISSUE THREAD

**Issue by Sxtanna** [JetBrains/compose-multiplatform#83]
When setting the icon on the window, the image is scaled very poorly, producing an extremely low resolution taskbar icon.

example:

![image](https://user-images.githubusercontent.com/20979389/98707956-9b9b4e80-234e-11eb-9118-f4bffd6c2cdd.png)

##### note both the taskbar and the decorator icons are poorly scaled

The actual image file is a 1,000 x 1,000 png.
![image](https://user-images.githubusercontent.com/20979389/98708040-b4a3ff80-234e-11eb-89fd-39e8769093b3.png)

**Comment by Sxtanna** [comment]
Relevant:
https://stackoverflow.com/questions/55188668/is-it-possible-to-give-awt-applications-sharp-taskbar-icons-in-windows-10

**Comment by hakanai** [comment]
Similar issue on the window icon. Same root cause - Compose loads only one bitmap and then "someone" scales it badly.

The ICO file provided contains a perfectly good 16x16 bitmap which looks fine

![image](https://github.com/JetBrains/compose-multiplatform/assets/43236/6374af2f-419e-4ec0-9201-316992a80f6e)

(lightness of image is mostly due to an HDR-related bug in Snipping Tool)

But what you get from Compose is:

![image](https://github.com/JetBrains/compose-multiplatform/assets/43236/ceb100ea-8be9-4208-842c-feaaa56ebd6e)

You can argue that the first image is discernably a rat, while the second image .....

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6025">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
