### ISSUE TITLE
SelectionContainer Text cannot copy text

### ISSUE THREAD

**Issue by D10NGYANG** [JetBrains/compose-multiplatform#931]
`SelectionContainer {
                Text(text ="你好")
}`
I ran the code, but could not copy the text from it.

macOS 11.4
Windows 10

**Comment by LouisCAD** [comment]
It's also non-native at all at the moment, which is not good because it breaks integration with OS features.

For instance, I use PopClip, an app that shows an actionable tooltip on text selection, and it never shows up on Compose for Desktop apps, while it does in Chrome, IntelliJ IDEA and everywhere else on my Mac.

**Comment by D10NGYANG** [comment]
> It's also non-native at all at the moment, which is not good because it breaks integration with OS features.
> 
> For instance, I use PopClip, an app that shows an actionable tooltip on text selection, and it never shows up on Compose for Desktop apps, while it does in Chrome, IntelliJ IDEA and everywhere else on my Mac.

Hi, do you have any other solutions?

**Comment by akurasov** [comment]
@D10NGYANG the fix was integrated into 1.0.0-alpha1-rc1. Should work now (works on my Mac).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6342">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
